#!/bin/sh

### BEGIN INIT INFO
# Provides:          raspotify
# Required-Start:    $network $syslog pulseaudio esound
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start raspotify daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

BITRATE=160
CACHE_ARGS=--disable-audio-cache
DEVICE_NAME=raspotify

[ -r /etc/default/raspotify ] && . /etc/default/raspotify

DAEMON=/usr/bin/librespot
PIDDIR=/var/run
LIBRESPOTPID=$PIDDIR/librespot.pid

LIBRESPOT_OPTS="--name ${DEVICE_NAME} --bitrate ${BITRATE} $CACHE_ARGS $OPTIONS"

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemon is there
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting the raspotify" "raspotify"

		start-stop-daemon --start --oknodo --chuid raspotify:raspotify --background --exec $DAEMON -- $LIBRESPOT_OPTS

		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping the raspotify" "raspotify"
		start-stop-daemon --stop --oknodo --exec $DAEMON
		log_end_msg $?
		;;

	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;

	status)
		status_of_proc -p $LIBRESPOTPID $DAEMON raspotify && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/raspotify {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac

